/run/initialize

/tracking/verbose 0
/hits/verbose 0

/gps/source/intensity 1
/gps/particle ion
/gps/ion 2 4 +2
/gps/pos/type Beam
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0

/gps/pos/shape Circle
/gps/pos/centre 0. 0. -0.1 cm
/gps/pos/radius 0. mm
/gps/pos/sigma_r 0. mm

/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d
/gps/ang/sigma_r 0. deg

/gps/ene/type Mono
/gps/ene/mono 5. MeV
/gps/ene/sigma 0. MeV

/analysis/setFileName alpha_5MeV

/run/beamOn 1000000
