/run/initialize

/tracking/verbose 0
/hits/verbose 0

/gps/source/intensity 1
/gps/particle mu-
/gps/pos/type Plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 -1

/gps/pos/shape Square
/gps/pos/centre 0. 6. 4.045 cm
/gps/pos/halfx 41. mm
/gps/pos/halfy 41. mm
/gps/pos/sigma_r 0. mm

/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 0 -1
/gps/ang/type beam1d
/gps/ang/sigma_r 0. deg

/gps/ene/type Mono
/gps/ene/mono 500. MeV
/gps/ene/sigma 0. MeV

/analysis/setFileName muon1

/run/beamOn 100000
